### ISSUE TITLE
Piecewise display encoding vs Pure Power

### ISSUE THREAD

**Issue by Joegenco** [KhronosGroup/ToneMapping#1]
https://github.com/KhronosGroup/ToneMapping/blob/42a0c99f77f7e2df32ab23d05972ac2d4557e709/PBR_Neutral/config.ocio#L52C1-L64C1

OCIO config defines a piecewise encoding function for the display. Although this is commonly used in such configs like ACES, it wrongly assumes that consumer and proffesional displays use an piecewise inverse power function.

Huge majority of contemporary displays use inverse pure power function instead. This should be just a 2.2 power for sRGB.

**Comment by elalish** [comment]
Thank you, that sounds reasonable. Also probably a nearly imperceptible change as well.

**Comment by Joegenco** [comment]
I wouldnt say that its imperceptible.

Here are some comparisons for you.
Assuming Linear Rec709 rendering space.
All going trough Khronos Neutral.


Piecewise Textures and Piecewise Display:
![KhronosNatural-PiecewiseTextures-PiecewiseDisplay](https://github.com/KhronosGroup/ToneMapping/assets/33637910/6d921528-205b-4fcf-9079-61282bfb64b2)
![image](https://github.com/KhronosGroup/ToneMapping/assets/33637910/f68a1ae5-1fc3-4020-95f0-1198783e4ae7)

Piecewise Textures and Pure Power Display:
![KhronosNatural-PiecewiseTextures-PurePowerDisplay](https://github.com/KhronosGroup/ToneMapping/assets/33637910/ddfa8bf8-9010-48e5-b298-0ee41565e214)
![image](https://github.com/KhronosGroup/ToneMapping/assets/33637910/830132e3-34aa-4f4a-a778-6ef919397f5d)

PurePower Textures and Pure Power Display:
![KhronosNatural-PurePowerTextures-PurePowerDisplay](https://github.com/KhronosGroup/ToneMapping/assets/33637910/fbc9eefe-12f8-4dc7-8387-4ad171876880)
![image](https://github.com/KhronosGroup/ToneMapping/assets/33637910/bdfa0509-c54e-4096-bab7-47a4e564f2ee)

-----
Difference between using piecewise textures and purepower assumed textures is minimal, but display changes drastically.
However I'd say piecewise textures vs pure power IS significant on certain situations.
Mind you all lights "colorpicking" also changes when "textures" power interpretation changes too.

A-B them yourself to see exacly the change. Pretty important when claiming "Neutral PBR" rendering. (If there can be such thing)

Also you could do some digging regarding contemprorary displays "inverse power functions" and not trust what Im claiming here. Its hard to find much data about how manufacturers implement the inverse function, but theres some out there alongside great research from Filmlight.
