### ISSUE TITLE
Can I use it on Octane Render? If so, how do I set it up? Thanks.

### ISSUE THREAD

**Issue by Jackbrobeep** [KhronosGroup/ToneMapping#6]
![image](https://github.com/user-attachments/assets/ef44981a-b55b-4c71-bd15-5e9f3789ec11)

**Comment by elalish** [comment]
It looks like you're in the right place. Did you try putting our https://github.com/KhronosGroup/ToneMapping/blob/main/PBR_Neutral/config.ocio file in there?

**Comment by Jackbrobeep** [comment]
I have tried, but it cannot automatically recognize the color space, and I don't know how to set its color space. The image shows AGX's OCIO, which can automatically recognize the correct color space.
![image](https://github.com/user-attachments/assets/9dcccc0d-1443-41bd-9c70-73087af27856)

**Comment by elalish** [comment]
I think this is a question for Octane, though I also asked an OCIO expert to see if they know.

**Comment by doug-walker** [comment]
The PBR Neutral config has a "Linear Rec.709" color space, which is probably what you would select for the "Manual(OCIO)" menu.

The tone-mapper itself would be used as a view. You should see a "PBR Neutral" option for your camera imager.

If you need more help, please reach out to Octane for support.

**Comment by Jackbrobeep** [comment]
My final setup, please check if it is correct.
![image](https://github.com/user-attachments/assets/2c685dfd-5161-4e1a-87a8-bf259aa03e7e)
![image](https://github.com/user-attachments/assets/afac59f3-2ec6-4e02-9e3e-923515a9d52c)

**Comment by doug-walker** [comment]
Looks like it should work.

**Comment by Jackbrobeep** [comment]
Thanks, it worked
